SELECT NOW(), CURDATE(), CURTIME();
SELECT YEAR(NOW()), MONTH(NOW()), DAY(NOW()), HOUR(NOW()), SECOND(NOW())
SELECT DAYNAMEE(NOW()), MONTHNAME(NOW())
SELECT EXTRACT(DAY FROM NOW()) -- this query is a part of standard SQL language